#!/usr/bin/env node
// Bulk translate Chinese strings to English in telegram-codex-bridge
const fs = require('fs');
const path = require('path');

const replacements = [
  // === src/telegram/ui-runtime.ts ===
  // Hub reminder
  ['💡 提示：需要查看运行卡片时，可发送 /hub。', '💡 Tip: Send /hub to bring back the runtime card.'],
  ['运行状态', 'Runtime Status'],
  ['"状态"', '"State"'],
  ['"进度"', '"Progress"'],
  ['收起计划清单', 'Hide Plan'],
  ['收起 Agent', 'Hide Agents'],
  ['查看详情', 'Inspect'],
  ['"命令"', '"Commands"'],
  ['"中断操作"', '"Interrupt"'],
  ['目录：', 'Hub: '],
  [' · 已完成', ' · Completed'],
  ['当前查看中的会话', 'Current viewed session'],
  ['其他运行中的会话', 'Other running sessions'],
  ['最近结束的会话', 'Recent ended sessions'],
  [' 个会话', ' sessions'],
  ['当前输入会话', 'Current input session'],
  ['当前查看中的运行会话', 'Focused running session'],
  ['当前查看中的会话', 'Focused session'],
  ['其他会话', 'Other sessions'],
  ['还有 ', '... '],
  [' 个会话未显示', ' more sessions not shown'],
  ['计划清单:', 'Plan:'],
  [' 个步骤', ' more steps'],
  [' 个 Agent', ' more agents'],
  ['计划详情', 'Plan Details'],
  [' 项计划', ' more plan items'],
  ['协作 Agent', 'Collab Agents'],
  ['"查看中"', '"Viewing"'],
  ['"当前输入"', '"Current input"'],
  ['"状态"', '"State"'],
  ['💡 提示：使用 /inspect 查看详情，使用 /interrupt 打断，使用 /status 查看状态。', '💡 Tip: Use /inspect for details, /interrupt to stop, /status for status.'],
  ['模型名', 'Model'],
  ['模型 + 推理强度', 'Model + Reasoning'],
  ['当前目录', 'Current Dir'],
  ['项目根目录', 'Project Root'],
  ['Git 分支', 'Git Branch'],
  ['剩余上下文', 'Context Remaining'],
  ['已用上下文', 'Context Used'],
  ['5 小时额度', '5h Limit'],
  ['周额度', 'Weekly Limit'],
  ['Codex 版本', 'Codex Version'],
  ['上下文窗口大小', 'Context Window'],
  ['已用 Token', 'Used Tokens'],
  ['累计输入 Token', 'Total Input Tokens'],
  ['累计输出 Token', 'Total Output Tokens'],
  ['会话 ID', 'Session ID'],
  ['会话名', 'Session Name'],
  ['项目名', 'Project Name'],
  ['项目路径（旧）', 'Project Path (legacy)'],
  ['模型 + 强度（旧）', 'Model + Effort (legacy)'],
  ['线程 ID（旧）', 'Thread ID (legacy)'],
  ['阻塞原因', 'Blocked Reason'],
  ['当前步骤', 'Current Step'],
  ['本次 Token', 'Last Token Usage'],
  ['累计 Token', 'Total Token Usage'],
  ['上下文窗口', 'Context Window'],
  ['最终答复已就绪', 'Final Answer Ready'],
  ['"无"', '"None"'],
  ['"已应用 Runtime 卡片字段"', '"Runtime card fields applied"'],
  ['"当前字段："', '"Current fields: "'],
  ['"已关闭 Runtime 卡片字段选择"', '"Runtime card field selection closed"'],
  ['当前没有已选字段。', 'No fields selected.'],
  ['"上一页"', '"Prev"'],
  ['"下一页"', '"Next"'],
  ['"保存并应用"', '"Save & Apply"'],
  ['"恢复默认"', '"Restore Default"'],
  ['"关闭"', '"Close"'],
  ['Runtime 卡片字段', 'Runtime Card Fields'],
  ['按按钮选择要显示的字段。', 'Tap buttons to select fields to display.'],
  ['选择顺序就是显示顺序；新选中的字段会追加到末尾。', 'Selection order is display order; new selections are appended.'],
  ['"当前分组："', '"Current group: "'],
  ['"已选字段："', '"Selected fields: "'],
  [' 个', ''],
  ['"分组页码："', '"Group page: "'],
  ['"总页码："', '"Total pages: "'],
  ['"展开详情"', '"Expand Details"'],
  ['"收起详情"', '"Collapse Details"'],
  ['"详情页："', '"Details page: "'],
  
  // === src/telegram/ui-final-answer.ts ===
  ['第 ', 'Page '],
  [' 页', ''],
  ['已折叠，共 ', 'Collapsed, '],
  ['页，点击"展开全文"查看。', ' pages total. Click "Expand" to view.'],
  ['已折叠，点击"展开全文"查看剩余内容。', 'Collapsed. Click "Expand" to view the rest.'],
  ['"展开全文"', '"Expand"'],
  ['"收起"', '"Collapse"'],
  ['"实施这个计划"', '"Implement this plan"'],
  ['"<b>最近输出</b>"', '"<b>Recent Output</b>"'],
  ['点击"展开最近输出"查看该会话最近一次输出。', 'Click "Expand Recent Output" to view the latest output for this session.'],
  ['该会话还没有最近输出。', 'This session has no recent output yet.'],
  ['"展开最近输出"', '"Expand Recent Output"'],
  ['"收起最近输出"', '"Collapse Recent Output"'],
  ['"展开方案"', '"Expand Plan"'],
  ['"收起方案"', '"Collapse Plan"'],
  ['已开始实施。', 'Implementation started.'],
  
  // === src/telegram/ui-messages.ts ===
  ['"会话名："', '"Session: "'],
  ['"项目："', '"Project: "'],
  ['"最近"', '"Recent"'],
  ['"本地发现"', '"Discovered"'],
  ['"有历史会话"', '"Has History"'],
  ['"浏览目录"', '"Browse"'],
  ['"手动输入路径"', '"Enter Path"'],
  ['"返回项目列表"', '"Back to Projects"'],
  ['"选择要浏览的根目录"', '"Select a root directory to browse"'],
  ['请发送要开始会话的目录路径，例如：/home/ubuntu/Repo/openclaw\\n发送 /cancel 返回项目列表。', 'Send the directory path to start a session, e.g. /home/ubuntu/Repo/openclaw\nSend /cancel to go back.'],
  ['要在这个目录中新建会话吗？', 'Create a new session in this directory?'],
  ['"路径："', '"Path: "'],
  ['"确认新建会话"', '"Confirm New Session"'],
  ['这个入口已下线。请使用浏览目录或手动输入路径。', 'This entry is no longer available. Please use Browse or Enter Path.'],
  ['"选择模型"', '"Select Model"'],
  ['当前配置：', 'Configured: '],
  ['当前生效：', 'Effective: '],
  ['"第 ', '"Page '],
  ['先选模型，再按该模型支持情况选择思考强度。', 'Select a model first, then choose reasoning effort based on its supported levels.'],
  ['"选择思考强度"', '"Select Reasoning Effort"'],
  ['模型：', 'Model: '],
  ['仅展示这个模型实际支持的档位。', 'Only showing effort levels supported by this model.'],
  ['"无"', '"None"'],
  ['"服务状态"', '"Bridge Status"'],
  ['"桥接状态："', '"Bridge state: "'],
  ['"平台连通："', '"Platform: "'],
  ['"异常"', '"Error"'],
  ['"正常"', '"OK"'],
  ['"配置完成："', '"Setup complete: "'],
  ['"否"', '"No"'],
  ['"是"', '"Yes"'],
  ['"Codex 可用："', '"Codex available: "'],
  ['"当前会话："', '"Active session: "'],
  ['"最近检查："', '"Last checked: "'],
  ['"问题："', '"Issues: "'],
  ['当前没有活动会话。', 'No active session.'],
  ['"当前会话"', '"Active Session"'],
  ['"状态："', '"State: "'],
  ['"模型配置："', '"Model config: "'],
  ['"模型生效："', '"Model effective: "'],
  ['"Bridge 会话 ID："', '"Bridge session ID: "'],
  ['"Codex 线程 ID："', '"Codex thread ID: "'],
  ['"尚未创建（首次发送任务后生成）"', '"Not yet created (generated on first task)"'],
  ['"最近 Turn ID："', '"Last Turn ID: "'],
  ['"暂无"', '"None"'],
  ['"上次结果："', '"Last result: "'],
  ['"已归档会话"', '"Archived Sessions"'],
  ['"最近会话"', '"Recent Sessions"'],
  ['暂无会话。', 'No sessions.'],
  ['"[当前] "', '"[Active] "'],
  ['"当前项目："', '"Current project: "'],
  ['"已新建会话"', '"Session Created"'],
  ['"已切换会话"', '"Session Switched"'],
  ['"已恢复 Codex 会话"', '"Codex Session Resumed"'],
  ['可恢复的 Codex 会话（', 'Resumable Codex sessions ('],
  ['页）', 'page)'],
  ['发送 /resume ', 'Send /resume '],
  ['<序号> 恢复。', '<index> to resume.'],
  ['上一页：/resume ', 'Previous: /resume '],
  ['下一页：/resume ', 'Next: /resume '],
  ['"已归档会话"', '"Session Archived"'],
  ['"已批量归档会话"', '"Sessions Bulk Archived"'],
  ['"已归档："', '"Archived: "'],
  ['"已跳过运行中："', '"Skipped (running): "'],
  ['"失败："', '"Failed: "'],
  ['当前没有活动会话，请发送 /new 选择项目。', 'No active session. Send /new to choose a project.'],
  ['"已恢复会话"', '"Session Restored"'],
  ['"当前会话已重命名为："', '"Session renamed to: "'],
  ['"当前项目别名已更新为："', '"Project alias updated to: "'],
  ['"已清除项目别名："', '"Project alias cleared: "'],
  ['"已收藏项目："', '"Project pinned: "'],
  ['"已关闭模型选择"', '"Model Selection Closed"'],
  ['"重命名会话"', '"Rename Session"'],
  ['"设置项目别名"', '"Set Project Alias"'],
  ['"清除项目别名"', '"Clear Project Alias"'],
  ['"要修改哪个名称？"', '"What would you like to rename?"'],
  ['"这个命令还没开放。"', '"This command is not yet available."'],
  ['"执行中"', '"Running"'],
  ['"已中断"', '"Interrupted"'],
  ['"失败"', '"Failed"'],
  ['"空闲"', '"Idle"'],
  ['配置 ', 'Configured '],
  [' / 生效 ', ' / Effective '],
  ['"桥接服务重启"', '"Bridge service restarted"'],
  ['"Codex 服务断开"', '"Codex service disconnected"'],
  ['"执行失败"', '"Execution failed"'],
  ['"未知原因"', '"Unknown reason"'],
  ['"上次已完成"', '"Last completed"'],
  ['"上次已中断"', '"Last interrupted"'],
  ['"上次失败"', '"Last failed"'],
  ['" [已配置]"', '" [Configured]"'],
  ['"清除模型/强度覆盖"', '"Clear model/effort override"'],
  ['"已配置"', '"Configured"'],
  ['"生效"', '"Effective"'],
  ['"默认（', '"Default ('],
  ['默认模型', 'Default'],
  ['"默认"', '"Default"'],
  ['"Default model"', '"Default"'],
  ['"default"', '"default"'],
  
  // === src/telegram/ui-browser.ts ===
  ['"文件浏览"', '"File Browser"'],
  ['"当前项目："', '"Project: "'],
  ['"当前位置："', '"Location: "'],
  ['"页码："', '"Page: "'],
  ['"模式："', '"Mode: "'],
  ['"只读浏览"', '"Read-only"'],
  ['"项目根"', '"Project Root"'],
  ['"当前目录为空。"', '"This directory is empty."'],
  ['"上一页"', '"Prev"'],
  ['"下一页"', '"Next"'],
  ['"上一级"', '"Up"'],
  ['"回到项目根"', '"Project Root"'],
  ['"刷新"', '"Refresh"'],
  ['"在当前目录新建会话"', '"New Session Here"'],
  ['"文件预览"', '"File Preview"'],
  ['"文件："', '"File: "'],
  ['"大小："', '"Size: "'],
  ['"修改时间："', '"Modified: "'],
  ['"预览页："', '"Preview page: "'],
  ['"仅预览前 48 KB。"', '"Preview limited to first 48 KB."'],
  ['"返回目录"', '"Back to Directory"'],
  ['"文件信息"', '"File Info"'],
  ['"类型："', '"Type: "'],
  ['"二进制或暂不支持预览"', '"Binary or preview not supported"'],
  ['"图片预览"', '"Image Preview"'],
  ['"确认新建会话"', '"Confirm New Session"'],
  ['"目录："', '"Directory: "'],
  ['"显示名："', '"Display name: "'],
  ['要在这个目录新建会话吗？', 'Create a new session in this directory?'],
  
  // === src/telegram/ui-commands.ts ===
  ['"打开命令面板"', '"Open Commands"'],
  ['"完整帮助"', '"Full Help"'],
  ['"编辑快捷指令"', '"Edit Commands"'],
  ['"快捷指令"', '"Commands"'],
  ['点击按钮即可执行桥接指令。', 'Tap a button to run a bridge command.'],
  ['"当前快捷指令："', '"Selected: "'],
  ['当前还没有已配置的快捷指令。', 'No quick commands configured yet.'],
  ['当前还没有选中的快捷指令。', 'No commands selected yet.'],
  ['"保存"', '"Save"'],
  ['"恢复默认"', '"Restore Default"'],
  ['点击按钮进行选择或移除。选择顺序就是显示顺序。', 'Tap buttons to select or remove. Selection order is display order.'],
  ['新选中的指令会追加到末尾。', 'New selections are appended at the end.'],
  ['"当前分组："', '"Current group: "'],
  ['"已选指令："', '"Selected: "'],
  ['"分组页码："', '"Group page: "'],
  ['"总页码："', '"Total pages: "'],
  
  // === src/telegram/commands.ts ===
  // These are in { zh: "..." } format - already have en translations, just replace zh with en text
  // This is handled separately
  
  // === src/service/rich-input-adapter.ts ===
  ['请逐字转写收到的语音，只返回转写文本，不要解释。', 'Transcribe the received voice message word by word. Return only the transcription text, no explanation.'],
  ['"已取消待发送的结构化输入。"', '"Structured input canceled."'],
  ['"当前会话已经变化，请重新发送结构化输入。"', '"Session has changed. Please resend the structured input."'],
  ['请继续发送要和', 'Please send the prompt to accompany the'],
  ['一起交给 Codex 的说明。', '.'],
  ['"当前没有活动会话。"', '"No active session."'],
  ['"用法：/local_image <图片路径> :: 任务说明"', '"Usage: /local_image <image-path> :: <prompt>"'],
  ['"这个本地图片路径不可用，请确认文件存在且是常见图片格式。"', '"Local image path unavailable. Please verify the file exists and is a common image format."'],
  ['本地图片：', 'Local image: '],
  ['"用法：/mention <path> :: 任务说明"', '"Usage: /mention <path> :: <prompt>"'],
  ['引用：', 'Mention: '],
  ['"用法：/attach <附件ID> :: 任务说明"', '"Usage: /attach <attachment-id> :: <prompt>"'],
  ['"找不到附件：', '"Attachment not found: '],
  ['当前无法把附件 ', 'Cannot convert attachment '],
  [' 转成 Codex 可读输入。', ' to Codex-readable input.'],
  ['附件：', 'Attachment: '],
  ['"最近附件暂时无法自动转成 Codex 可读输入，请改用支持文本提取的文件，或稍后再试。"', '"Recent attachment cannot be converted to Codex input. Please try a text-extractable file or try again later."'],
  ['"未启用语音输入。"', '"Voice input not enabled."'],
  ['"请先发送 /new 选择项目。"', '"Please send /new to choose a project first."'],
  ['"已收到语音，正在排队转写。前方还有 ', '"Voice received, queued for transcription. '],
  [' 条语音。"', ' voice(s) ahead."'],
  ['"已收到语音，正在转写。"', '"Voice received, transcribing."'],
  ['"暂时无法读取这张图片，请稍后重试。"', '"Unable to read this image. Please try again later."'],
  ['"暂时无法读取这段语音，请稍后重试。"', '"Unable to read this voice message. Please try again later."'],
  ['"OpenAI 语音转写失败，正在尝试 realtime 兜底。"', '"OpenAI voice transcription failed, trying realtime fallback."'],
  ['"语音输入失败：', '"Voice input failed: '],
  ['"语音已转写，但对应会话已不可用，请重新发送。"', '"Voice transcribed, but the session is no longer available. Please resend."'],
  ['"语音转写：', '"Voice transcription: '],
  ['"暂时无法处理这段语音，请稍后重试。"', '"Unable to process this voice message. Please try again later."'],
  ['"Codex 服务暂时不可用，请稍后重试。"', '"Codex service temporarily unavailable. Please try again later."'],
  ['"当前项目仍在执行，请等待完成或发送 /interrupt。"', '"Current project is still running. Please wait or send /interrupt."'],
  ['已记录', 'Recorded'],
  ['请继续发送任务说明，或发送 /cancel 取消。', 'Please send your prompt, or /cancel to abort.'],
  ['"这条语音对应的会话已不可用，请重新选择会话后再试。"', '"The session for this voice message is no longer available. Please select a session and try again."'],
  ['当前 Codex 模型不支持 realtime 音频输入。', 'Current Codex model does not support realtime audio input.'],
  ['系统里找不到 ffmpeg：', 'ffmpeg not found on system: '],
  ['已接收文件附件：\\n', 'File attachment received:\\n'],
  ['已接收 ', 'Received '],
  [' 个文件附件：\\n', ' file attachments:\\n'],
  ['下一条消息会自动带上最近附件；也可用 /attach <附件ID> :: 任务说明；发送 /cancel 可取消。', 'Next message will automatically include the recent attachment(s). You can also use /attach <id> :: <prompt>. Send /cancel to cancel.'],
  ['以下附件未能完成解析：\\n', 'The following attachments could not be parsed:\\n'],
  ['以下是附件《', 'Below is the extracted content of attachment "'],
  ['》的提取内容：\\n\\n', '":\\n\\n'],
  ['》的提取内容（已截断）：\\n\\n', '" (truncated):\\n\\n'],
  ['"图片"', '"Image"'],
  [' 张图片', ' image(s)'],
  
  // === src/activity/tracker.ts ===
  ['交互已完成：', 'Interaction completed: '],
  ['"配置警告"', '"Config warning"'],
  ['"弃用提示"', '"Deprecation notice"'],
  ['"技能列表已刷新"', '"Skills list refreshed"'],
  ['"上下文已压缩"', '"Context compacted"'],
  [' 个文件', ' file(s)'],
  ['差异更新：', 'Diff updated: '],
  ['差异已更新', 'Diff updated'],
  ['终端输入请求未转发到当前控制面：', 'Terminal input request not forwarded to current control surface: '],
  ['终端输入请求未转发到当前控制面', 'Terminal input request not forwarded to current control surface'],
  ['模型已改道：', 'Model rerouted: '],
  
  // === src/interactions/normalize.ts ===
  ['"目录：${cwd}"', '"Directory: ${cwd}"'],
  ['"Codex 需要命令批准"', '"Codex requires command approval"'],
  ['"命令审批"', '"Command Approval"'],
  ['"Codex 需要文件变更批准"', '"Codex requires file change approval"'],
  ['"文件变更审批"', '"File Change Approval"'],
  ['"Codex 需要补丁批准"', '"Codex requires patch approval"'],
  ['"兼容补丁审批"', '"Patch Approval (compat)"'],
  ['"授权根目录：${grantRoot}"', '"Grant root: ${grantRoot}"'],
  ['"兼容命令审批"', '"Command Approval (compat)"'],
  ['"Codex 需要权限批准"', '"Codex requires permission approval"'],
  ['"权限审批"', '"Permission Approval"'],
  ['"Codex 需要更多信息"', '"Codex needs more information"'],
  ['"MCP 需要用户确认"', '"MCP requires user confirmation"'],
  ['"MCP 发起了一个需要你确认的请求。"', '"MCP has initiated a request that requires your confirmation."'],
  ['"MCP 需要更多信息"', '"MCP needs more information"'],
  ['"从下方选一个选项。"', '"Choose an option below."'],
  ['"可选值：', '"Allowed values: '],
  ['。多个值请用逗号分隔。"', '". Separate multiple values with commas."'],
  ['"多个值请用逗号分隔。"', '"Separate multiple values with commas."'],
  ['"请选择是或否。"', '"Please select Yes or No."'],
  ['"是"', '"Yes"'],
  ['"返回 true"', '"Returns true"'],
  ['"否"', '"No"'],
  ['"返回 false"', '"Returns false"'],
  ['"请直接发送整数。"', '"Please enter an integer."'],
  ['"请直接发送数字。"', '"Please enter a number."'],
  ['"请直接发送文字回答。"', '"Please enter a text answer."'],
  ['"请提供 ', '"Please provide '],
  ['。"', '."'],
  ['"这是必填项。"', '"This is required."'],
  ['"这是可选项。"', '"This is optional."'],
  ['"批准"', '"Approve"'],
  ['"本会话内总是批准"', '"Always approve for this session"'],
  ['"拒绝"', '"Decline"'],
  ['"取消本次交互"', '"Cancel this interaction"'],
  ['"批准并记住命令规则"', '"Approve and remember command rule"'],
  ['"批准并保存网络规则（', '"Approve and save network rule ("'],
  ['"批准并保存网络规则"', '"Approve and save network rule"'],
  ['"跳过"', '"Skip"'],
  ['"保留为空"', '"Leave empty"'],
  ['以及另外 ', 'and '],
  [' 个文件', ' more file(s)'],
];

const files = [
  'src/telegram/ui-runtime.ts',
  'src/telegram/ui-final-answer.ts',
  'src/telegram/ui-messages.ts',
  'src/telegram/ui-browser.ts',
  'src/telegram/ui-commands.ts',
  'src/service/rich-input-adapter.ts',
  'src/activity/tracker.ts',
  'src/interactions/normalize.ts',
];

const baseDir = '/home/pamekar/Projects/telegram-codex-bridge';

let totalReplacements = 0;

for (const file of files) {
  const filePath = path.join(baseDir, file);
  let content = fs.readFileSync(filePath, 'utf8');
  let fileReplacements = 0;
  
  for (const [from, to] of replacements) {
    if (content.includes(from)) {
      content = content.split(from).join(to);
      fileReplacements++;
    }
  }
  
  if (fileReplacements > 0) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`${file}: ${fileReplacements} replacements`);
    totalReplacements += fileReplacements;
  }
}

console.log(`\nTotal replacements: ${totalReplacements}`);
